name: docker-compose

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: docker-compose build
    - name: install
      run: docker-compose run web composer install
#     - name: load fixtures
#       run: docker-compose run web app/console doctrine:fixtures:load --purge-with-truncate
    - name: test
      run: |
        docker-compose run web composer install --no-interaction
        docker-compose run web mkdir -p app/Resources/views/client
        docker-compose run web touch app/Resources/views/client/index.html.twig
        docker-compose run web bin/phpunit --configuration app
